# HyperParameter Tunning (XGBC)

In [1]:
# Imports

import os
import sys
import optuna
import pandas as pd
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split , RandomizedSearchCV , cross_val_score , StratifiedKFold
from scipy.stats import uniform , randint
from sklearn.metrics import f1_score , accuracy_score
from sklearn.metrics import roc_auc_score


sys.path.append(os.path.abspath("../src"))
sys.path.append(os.path.abspath(".."))

from preprocessing import get_X_y

C:\Users\sailj\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Data Load

df = pd.read_csv(r"../dataset/train.csv")

df

,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender,Customer Type,Type of Travel,Class,satisfaction
0,0,36,694,4,4,4,3,1,4,1,...,4,3,1,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
1,1,56,651,5,5,5,5,5,4,4,...,5,4,3,0,0.0,Male,Loyal Customer,Business travel,Business,True
2,2,31,1371,3,4,2,5,3,3,3,...,4,5,3,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
3,3,10,1616,3,5,3,3,3,3,3,...,3,4,3,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False
4,4,23,481,3,4,3,4,5,3,5,...,5,3,5,5,0.0,Female,disloyal Customer,Business travel,Eco,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699630,699630,57,612,2,1,1,1,1,3,3,...,2,2,4,0,0.0,Female,Loyal Customer,Business travel,Eco,False
699631,699631,30,862,2,2,2,3,4,2,4,...,4,2,4,24,34.0,Female,disloyal Customer,Business travel,Eco,False
699632,699632,49,3148,5,5,5,5,4,4,4,...,5,5,5,0,0.0,Male,Loyal Customer,Business travel,Business,True
699633,699633,61,679,5,2,2,2,5,4,4,...,5,5,1,0,0.0,Female,Loyal Customer,Business travel,Eco,True
699634,699634,42,813,1,1,0,4,3,0,3,...,3,4,3,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False

In [3]:
# Preprocessing

X_train , y_train = get_X_y(df)

X_train

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Gender,Customer Type,Type of Travel,Class,Total Delay
0,36,694,4,4,4,3,1,4,1,1,3,4,4,3,1,Female,Loyal Customer,Personal Travel,Eco,0.0
1,56,651,5,5,5,5,5,4,4,5,5,5,5,4,3,Male,Loyal Customer,Business travel,Business,0.0
2,31,1371,3,4,2,5,3,3,3,3,4,3,4,5,3,Female,Loyal Customer,Personal Travel,Eco,0.0
3,10,1616,3,5,3,3,3,3,3,3,4,5,3,4,3,Male,Loyal Customer,Personal Travel,Eco,0.0
4,23,481,3,4,3,4,5,3,5,5,5,4,5,3,5,Female,disloyal Customer,Business travel,Eco,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699630,57,612,2,1,1,1,1,3,3,2,2,2,2,2,4,Female,Loyal Customer,Business travel,Eco,0.0
699631,30,862,2,2,2,3,4,2,4,4,2,5,4,2,4,Female,disloyal Customer,Business travel,Eco,58.0
699632,49,3148,5,5,5,5,4,4,4,5,5,5,5,5,5,Male,Loyal Customer,Business travel,Business,0.0
699633,61,679,5,2,2,2,5,4,4,5,4,5,5,5,1,Female,Loyal Customer,Business travel,Eco,0.0
699634,42,813,1,1,0,4,3,0,3,3,4,4,3,4,3,Male,Loyal Customer,Personal Travel,Eco,0.0

In [4]:
# Data Prep

cat_cols = X_train.select_dtypes(include = ["string" , "object"]).columns

preprocess = ColumnTransformer([
    ("cat" , OneHotEncoder(handle_unknown = "ignore") , cat_cols)
] , remainder = "passthrough")

model = Pipeline([
    ("preprocess" , preprocess) ,
    ("xgbc" , XGBClassifier())
])

In [45]:
def objective(trial) :

    params = {

        "xgbc__n_estimators" : trial.suggest_int(
            "n_estimators" ,
            200 ,
            2000
        ) ,

        "xgbc__max_depth" : trial.suggest_int(
            "max_depth" ,
            2 , 
            12
        ) ,

        "xgbc__learning_rate" : trial.suggest_float(
            "learning_rate" ,
            0.005 ,
            0.3 ,
            log = True
        ) ,

        "xgbc__min_child_weight" : trial.suggest_int(
            "min_child_weight" ,
            1 ,
            30
        ) ,

        "xgbc__gamma" : trial.suggest_float(
            "gamma" ,
            1e-8 ,
            10 , 
            log = True
        ) ,

        "xgbc__reg_alpha" : trial.suggest_float(
            "reg_alpha" ,
            1e-8 ,
            100 ,
            log = True
        ) ,

        "xgbc__reg_lambda" : trial.suggest_float(
            "reg_lambda" ,
            1e-8 , 
            100 ,
            log = True
        ) ,

        "xgbc__subsample" : trial.suggest_float(
            "subsample" ,
            0.6 , 
            1.0
        ) ,

        "xgbc__colsample_bytree" : trial.suggest_float(
            "colsample_bytree" ,
            0.6 ,
            1.0 
        ) ,
        
        "xgbc__eval_metric" : "auc" ,
        "xgbc__objective"  : 'binary:logistic' , 
        "xgbc__n_jobs" : 1 ,
        "xgbc__random_state" : 42
    }

    model.set_params(**params)

    cv = StratifiedKFold(
        n_splits = 3 ,
        shuffle = True ,
        random_state = 42
    )

    scores = cross_val_score(
        model ,
        X_train ,
        y_train ,
        cv = cv ,
        scoring = "roc_auc" ,
        n_jobs = -1
    )

    return scores.mean()

study = optuna.create_study(
    study_name = "Study 1" ,
    direction = "maximize"
)

study.optimize(
    objective ,
    n_trials = 30
)

print("Best CV ROC-AUC:", study.best_value)
print("Best Parameters:")
print(study.best_params)

[I 2026-10-09 00:32:55,866] A new study created in memory with name: Study 1
[I 2026-10-09 00:33:44,120] Trial 0 finished with value: 0.9550002218435187 and parameters: {'n_estimators': 613, 'max_depth': 3, 'learning_rate': 0.03119854852818446, 'min_child_weight': 16, 'gamma': 1.827370577473892, 'reg_alpha': 5.078682909856213, 'reg_lambda': 0.018527480502598278, 'subsample': 0.669008652726127, 'colsample_bytree': 0.8212834980354242}. Best is trial 0 with value: 0.9550002218435187.
[I 2026-10-09 00:35:17,647] Trial 1 finished with value: 0.9582006912947053 and parameters: {'n_estimators': 520, 'max_depth': 12, 'learning_rate': 0.04458577734011148, 'min_child_weight': 23, 'gamma': 3.3767826929635685e-05, 'reg_alpha': 8.361237069149528e-05, 'reg_lambda': 2.164313018123939e-08, 'subsample': 0.6428652185208442, 'colsample_bytree': 0.7621621152676328}. Best is trial 1 with value: 0.9582006912947053.
[I 2026-10-09 00:35:59,253] Trial 2 finished with value: 0.9563160604878168 and parameters: {'n_estimators': 207, 'max_depth': 10, 'learning_rate': 0.008086635326079512, 'min_child_weight': 13, 'gamma': 1.1965762645225775e-07, 'reg_alpha': 0.043895832256576395, 'reg_lambda': 0.001968208986395682, 'subsample': 0.8418072181141407, 'colsample_bytree': 0.6770423678709068}. Best is trial 1 with value: 0.9582006912947053.
[I 2026-10-09 00:36:53,255] Trial 3 finished with value: 0.9577485111839668 and parameters: {'n_estimators': 588, 'max_depth': 6, 'learning_rate': 0.0331885066489938, 'min_child_weight': 16, 'gamma': 1.946332791423066, 'reg_alpha': 0.010535733341123442, 'reg_lambda': 1.6266014938231787e-05, 'subsample': 0.9938024039424839, 'colsample_bytree': 0.9436329037000679}. Best is trial 1 with value: 0.9582006912947053.
[I 2026-10-09 00:39:59,113] Trial 4 finished with value: 0.9518189697673046 and parameters: {'n_estimators': 1317, 'max_depth': 9, 'learning_rate': 0.18471247046765624, 'min_child_weight': 2, 'gamma': 0.0253587777904957, 'reg_alpha': 3.3168787009457857e-06, 'reg_lambda': 4.176201522401488e-06, 'subsample': 0.895316982872929, 'colsample_bytree': 0.7927286737299994}. Best is trial 1 with value: 0.9582006912947053.
[I 2026-10-09 00:42:36,224] Trial 5 finished with value: 0.9583245620060148 and parameters: {'n_estimators': 1615, 'max_depth': 7, 'learning_rate': 0.024397403798709128, 'min_child_weight': 3, 'gamma': 0.0018983651630928588, 'reg_alpha': 7.811902643569e-08, 'reg_lambda': 3.9874297010826887e-07, 'subsample': 0.9797020714623039, 'colsample_bytree': 0.9308152957504118}. Best is trial 5 with value: 0.9583245620060148.
[I 2026-10-09 00:46:08,384] Trial 6 finished with value: 0.9567263635007901 and parameters: {'n_estimators': 1813, 'max_depth': 8, 'learning_rate': 0.07309557977288964, 'min_child_weight': 14, 'gamma': 0.16203847769246424, 'reg_alpha': 0.012633247449884467, 'reg_lambda': 0.003754267554510404, 'subsample': 0.8213388901629937, 'colsample_bytree': 0.9859915829138953}. Best is trial 5 with value: 0.9583245620060148.
[I 2026-10-09 00:48:32,926] Trial 7 finished with value: 0.9561940884316433 and parameters: {'n_estimators': 1797, 'max_depth': 2, 'learning_rate': 0.13689924226909378, 'min_child_weight': 30, 'gamma': 2.3920124792379068e-06, 'reg_alpha': 0.43403699161704573, 'reg_lambda': 0.02860725000561584, 'subsample': 0.7850679048977667, 'colsample_bytree': 0.8679706284802731}. Best is trial 5 with value: 0.9583245620060148.
[I 2026-10-09 00:49:32,265] Trial 8 finished with value: 0.9475016632908108 and parameters: {'n_estimators': 715, 'max_depth': 2, 'learning_rate': 0.009819005372874164, 'min_child_weight': 3, 'gamma': 0.0012517251372450781, 'reg_alpha': 0.390281187226257, 'reg_lambda': 0.0011524941736441678, 'subsample': 0.7305148407401952, 'colsample_bytree': 0.8471791552787244}. Best is trial 5 with value: 0.9583245620060148.
[I 2026-10-09 00:52:43,689] Trial 9 finished with value: 0.9582662993179092 and parameters: {'n_estimators': 1707, 'max_depth': 7, 'learning_rate': 0.007673550693984301, 'min_child_weight': 22, 'gamma': 1.4650452547721417e-08, 'reg_alpha': 0.0009373955582083415, 'reg_lambda': 1.3064768442137729, 'subsample': 0.9499134868437421, 'colsample_bytree': 0.6509913320003813}. Best is trial 5 with value: 0.9583245620060148.
[I 2026-10-09 00:54:36,673] Trial 10 finished with value: 0.9572730603914704 and parameters: {'n_estimators': 1202, 'max_depth': 5, 'learning_rate': 0.2852083956632116, 'min_child_weight': 6, 'gamma': 0.0003012199046966805, 'reg_alpha': 1.6428877342327392e-07, 'reg_lambda': 36.20428854509565, 'subsample': 0.7452051374368212, 'colsample_bytree': 0.6024716550093692}. Best is trial 5 with value: 0.9583245620060148.
[I 2026-10-09 00:57:05,577] Trial 11 finished with value: 0.9584810766255671 and parameters: {'n_estimators': 1469, 'max_depth': 7, 'learning_rate': 0.015347245847655285, 'min_child_weight': 30, 'gamma': 1.24413161146303e-08, 'reg_alpha': 3.49282448854077e-08, 'reg_lambda': 23.734360741143337, 'subsample': 0.9885164630421572, 'colsample_bytree': 0.7162481189217555}. Best is trial 11 with value: 0.9584810766255671.
[I 2026-10-09 00:59:09,512] Trial 12 finished with value: 0.9577756404131348 and parameters: {'n_estimators': 1398, 'max_depth': 5, 'learning_rate': 0.016671207091702986, 'min_child_weight': 8, 'gamma': 1.8486225612508378e-06, 'reg_alpha': 5.066394505388211e-08, 'reg_lambda': 1.976372728944481e-08, 'subsample': 0.9951534840483346, 'colsample_bytree': 0.721810035175716}. Best is trial 11 with value: 0.9584810766255671.
[I 2026-10-09 01:02:25,975] Trial 13 finished with value: 0.9587184950167749 and parameters: {'n_estimators': 1528, 'max_depth': 10, 'learning_rate': 0.016049793769125548, 'min_child_weight': 30, 'gamma': 0.00628289414096616, 'reg_alpha': 1.4182527083521002e-08, 'reg_lambda': 63.67109063007865, 'subsample': 0.9192580300880404, 'colsample_bytree': 0.9187012880525618}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:04:51,680] Trial 14 finished with value: 0.9586384486297561 and parameters: {'n_estimators': 1036, 'max_depth': 11, 'learning_rate': 0.015519491139467777, 'min_child_weight': 30, 'gamma': 3.0510340004605783e-05, 'reg_alpha': 4.905417057757324e-06, 'reg_lambda': 65.6787362325715, 'subsample': 0.9061514241579132, 'colsample_bytree': 0.9004984169198611}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:08:24,337] Trial 15 finished with value: 0.9583506325360954 and parameters: {'n_estimators': 1136, 'max_depth': 12, 'learning_rate': 0.005757459175801893, 'min_child_weight': 24, 'gamma': 3.956983003515031e-05, 'reg_alpha': 5.385061721256299e-06, 'reg_lambda': 1.0154102583648767, 'subsample': 0.9058152713430911, 'colsample_bytree': 0.8943058824107641}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:10:38,155] Trial 16 finished with value: 0.9586606557279369 and parameters: {'n_estimators': 987, 'max_depth': 10, 'learning_rate': 0.01576259338919603, 'min_child_weight': 26, 'gamma': 0.017052240461726355, 'reg_alpha': 1.601570884204973e-06, 'reg_lambda': 1.340833863877761, 'subsample': 0.8983724725795935, 'colsample_bytree': 0.9941104128486191}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:14:52,204] Trial 17 finished with value: 0.9560146104430584 and parameters: {'n_estimators': 1988, 'max_depth': 10, 'learning_rate': 0.06852191627187397, 'min_child_weight': 26, 'gamma': 0.020600822494115437, 'reg_alpha': 1.0430085963419583e-08, 'reg_lambda': 1.0359217359545214, 'subsample': 0.8593496997687432, 'colsample_bytree': 0.9777300168023738}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:16:50,159] Trial 18 finished with value: 0.9584692924391457 and parameters: {'n_estimators': 898, 'max_depth': 9, 'learning_rate': 0.011872873991198844, 'min_child_weight': 26, 'gamma': 0.08591611405396554, 'reg_alpha': 1.7502895309996464e-06, 'reg_lambda': 3.098859514133978, 'subsample': 0.9347843458543175, 'colsample_bytree': 0.9515694535926261}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:18:54,613] Trial 19 finished with value: 0.9586191747577661 and parameters: {'n_estimators': 932, 'max_depth': 10, 'learning_rate': 0.02103315944970825, 'min_child_weight': 18, 'gamma': 0.003274178823919143, 'reg_alpha': 0.00010653337949557767, 'reg_lambda': 0.14178020578739375, 'subsample': 0.8582359994722949, 'colsample_bytree': 0.9093695519204109}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:19:32,572] Trial 20 finished with value: 0.9547868648565734 and parameters: {'n_estimators': 257, 'max_depth': 11, 'learning_rate': 0.005076626691040156, 'min_child_weight': 21, 'gamma': 6.795276738027621, 'reg_alpha': 6.310116790768266e-07, 'reg_lambda': 8.48514304015531, 'subsample': 0.8089029273774425, 'colsample_bytree': 0.9804153773523139}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:21:52,803] Trial 21 finished with value: 0.9585752121935608 and parameters: {'n_estimators': 989, 'max_depth': 11, 'learning_rate': 0.01386515580377771, 'min_child_weight': 28, 'gamma': 0.00021062115682872134, 'reg_alpha': 2.0771339925514946e-05, 'reg_lambda': 82.87205693907748, 'subsample': 0.9020078665604034, 'colsample_bytree': 0.8860264585656674}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:24:25,186] Trial 22 finished with value: 0.9586656464279403 and parameters: {'n_estimators': 1122, 'max_depth': 11, 'learning_rate': 0.021352333812287273, 'min_child_weight': 27, 'gamma': 4.515016161748118e-06, 'reg_alpha': 4.5700919391689037e-07, 'reg_lambda': 88.31474633924915, 'subsample': 0.9449190991824757, 'colsample_bytree': 0.9220005160883193}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:25:49,012] Trial 23 finished with value: 0.9584825472852199 and parameters: {'n_estimators': 792, 'max_depth': 9, 'learning_rate': 0.04656240606599754, 'min_child_weight': 27, 'gamma': 1.097088020018723e-06, 'reg_alpha': 3.584824533445335e-07, 'reg_lambda': 0.3061587023383152, 'subsample': 0.9561680575942587, 'colsample_bytree': 0.9468784379136753}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:28:36,339] Trial 24 finished with value: 0.9583676945185419 and parameters: {'n_estimators': 1253, 'max_depth': 11, 'learning_rate': 0.024437735625325294, 'min_child_weight': 25, 'gamma': 0.2682454562453993, 'reg_alpha': 1.3502323065474005e-08, 'reg_lambda': 7.254915773307089, 'subsample': 0.8772648583013388, 'colsample_bytree': 0.9989103969533655}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:32:19,511] Trial 25 finished with value: 0.9586425935416564 and parameters: {'n_estimators': 1482, 'max_depth': 12, 'learning_rate': 0.010187531533245257, 'min_child_weight': 21, 'gamma': 0.010706357825118301, 'reg_alpha': 4.539534194279084e-07, 'reg_lambda': 0.1723539724705196, 'subsample': 0.9307628762559472, 'colsample_bytree': 0.8329065121002179}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:34:21,826] Trial 26 finished with value: 0.9586817706323351 and parameters: {'n_estimators': 1131, 'max_depth': 8, 'learning_rate': 0.019727084556966906, 'min_child_weight': 28, 'gamma': 0.000525916843458951, 'reg_alpha': 5.6690511769550357e-05, 'reg_lambda': 9.731391821411547, 'subsample': 0.9323942105728871, 'colsample_bytree': 0.9272578356407549}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:37:06,659] Trial 27 finished with value: 0.9585336285669879 and parameters: {'n_estimators': 1540, 'max_depth': 8, 'learning_rate': 0.03960563999470032, 'min_child_weight': 19, 'gamma': 0.00030137322421184886, 'reg_alpha': 0.0003336323065366053, 'reg_lambda': 20.70988486754507, 'subsample': 0.9486431190998276, 'colsample_bytree': 0.8621621476258022}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:39:23,916] Trial 28 finished with value: 0.9578235785656496 and parameters: {'n_estimators': 1129, 'max_depth': 8, 'learning_rate': 0.06490358559357841, 'min_child_weight': 28, 'gamma': 8.558663730838376e-06, 'reg_alpha': 2.4628046116447404e-05, 'reg_lambda': 6.7404798954170175, 'subsample': 0.6007677966717075, 'colsample_bytree': 0.9216028356333238}. Best is trial 13 with value: 0.9587184950167749.
[I 2026-10-09 01:41:08,091] Trial 29 finished with value: 0.9570107803138409 and parameters: {'n_estimators': 1331, 'max_depth': 4, 'learning_rate': 0.021407940753681562, 'min_child_weight': 29, 'gamma': 1.8852110042749847e-07, 'reg_alpha': 0.002082275074687835, 'reg_lambda': 93.4403702956826, 'subsample': 0.9627497345168674, 'colsample_bytree': 0.8050151709324845}. Best is trial 13 with value: 0.9587184950167749.

Best CV ROC-AUC: 0.9587184950167749
Best Parameters:
{'n_estimators': 1528, 'max_depth': 10, 'learning_rate': 0.016049793769125548, 'min_child_weight': 30, 'gamma': 0.00628289414096616, 'reg_alpha': 1.4182527083521002e-08, 'reg_lambda': 63.67109063007865, 'subsample': 0.9192580300880404, 'colsample_bytree': 0.9187012880525618}

In [5]:
# 1st Try

def objective(trial) :

    params = {

        "xgbc__n_estimators" : trial.suggest_int(
            "n_estimators" ,
            200 ,
            2000
        ) ,

        "xgbc__max_depth" : trial.suggest_int(
            "max_depth" ,
            2 , 
            12
        ) ,

        "xgbc__learning_rate" : trial.suggest_float(
            "learning_rate" ,
            0.005 ,
            0.3 ,
            log = True
        ) ,

        "xgbc__min_child_weight" : trial.suggest_int(
            "min_child_weight" ,
            1 ,
            30
        ) ,

        "xgbc__gamma" : trial.suggest_float(
            "gamma" ,
            1e-8 ,
            10 , 
            log = True
        ) ,

        "xgbc__reg_alpha" : trial.suggest_float(
            "reg_alpha" ,
            1e-8 ,
            100 ,
            log = True
        ) ,

        "xgbc__reg_lambda" : trial.suggest_float(
            "reg_lambda" ,
            1e-8 , 
            100 ,
            log = True
        ) ,

        "xgbc__subsample" : trial.suggest_float(
            "subsample" ,
            0.6 , 
            1.0
        ) ,

        "xgbc__colsample_bytree" : trial.suggest_float(
            "colsample_bytree" ,
            0.6 ,
            1.0 
        ) ,
        
        "xgbc__eval_metric" : "auc" ,
        "xgbc__objective"  : 'binary:logistic' , 
        "xgbc__n_jobs" : 1 ,
        "xgbc__random_state" : 42
    }

    model.set_params(**params)

    cv = StratifiedKFold(
        n_splits = 3 ,
        shuffle = True ,
        random_state = 42
    )

    scores = cross_val_score(
        model ,
        X_train ,
        y_train ,
        cv = cv ,
        scoring = "roc_auc" ,
        n_jobs = -1
    )

    return scores.mean()

study = optuna.create_study(
    study_name = "Study 1" ,
    direction = "maximize"
)

study.optimize(
    objective ,
    n_trials = 30
)

print("Best CV ROC-AUC:", study.best_value)
print("Best Parameters:")
print(study.best_params)

[I 2026-10-10 20:10:17,711] A new study created in memory with name: Study 1
[I 2026-10-10 20:11:26,068] Trial 0 finished with value: 0.9572138207950248 and parameters: {'n_estimators': 905, 'max_depth': 6, 'learning_rate': 0.168910508162265, 'min_child_weight': 4, 'gamma': 8.371635644913104e-07, 'reg_alpha': 5.482191785113308e-07, 'reg_lambda': 0.6418491063285837, 'subsample': 0.8688879754924974, 'colsample_bytree': 0.927153735052281}. Best is trial 0 with value: 0.9572138207950248.
[I 2026-10-10 20:15:30,593] Trial 1 finished with value: 0.9578690564863805 and parameters: {'n_estimators': 1094, 'max_depth': 11, 'learning_rate': 0.023233937741175534, 'min_child_weight': 4, 'gamma': 0.0019634924517776295, 'reg_alpha': 6.865830945849653e-08, 'reg_lambda': 5.488780807737366e-07, 'subsample': 0.638209381041302, 'colsample_bytree': 0.7088382504048041}. Best is trial 1 with value: 0.9578690564863805.
[I 2026-10-10 20:18:00,904] Trial 2 finished with value: 0.958194998507185 and parameters: {'n_estimators': 893, 'max_depth': 7, 'learning_rate': 0.04498524943105096, 'min_child_weight': 2, 'gamma': 1.2567064377047873e-07, 'reg_alpha': 45.586074536736554, 'reg_lambda': 3.4065024885934195e-05, 'subsample': 0.7983281398977984, 'colsample_bytree': 0.6580399115730883}. Best is trial 2 with value: 0.958194998507185.
[I 2026-10-10 20:20:18,915] Trial 3 finished with value: 0.9565173307283822 and parameters: {'n_estimators': 1162, 'max_depth': 4, 'learning_rate': 0.014722898483433767, 'min_child_weight': 9, 'gamma': 0.445604066000657, 'reg_alpha': 0.03998896167254228, 'reg_lambda': 0.2105565319036823, 'subsample': 0.9471739442634622, 'colsample_bytree': 0.98051779820232}. Best is trial 2 with value: 0.958194998507185.
[I 2026-10-10 20:24:42,849] Trial 4 finished with value: 0.9587043183875325 and parameters: {'n_estimators': 1268, 'max_depth': 12, 'learning_rate': 0.019047511499818245, 'min_child_weight': 15, 'gamma': 0.0012073553969152895, 'reg_alpha': 29.436468296748476, 'reg_lambda': 7.14089185714042e-05, 'subsample': 0.9469845675276354, 'colsample_bytree': 0.7552967054500254}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 20:27:53,229] Trial 5 finished with value: 0.9583136129061396 and parameters: {'n_estimators': 1138, 'max_depth': 6, 'learning_rate': 0.020531617837521162, 'min_child_weight': 15, 'gamma': 4.196048001831225e-08, 'reg_alpha': 7.447992765417709, 'reg_lambda': 0.020802101202668507, 'subsample': 0.6452829920839936, 'colsample_bytree': 0.6545959336844739}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 20:31:41,162] Trial 6 finished with value: 0.9522858560130297 and parameters: {'n_estimators': 1331, 'max_depth': 8, 'learning_rate': 0.26760728249959553, 'min_child_weight': 16, 'gamma': 7.072880019556315e-08, 'reg_alpha': 1.9117326383436574e-05, 'reg_lambda': 0.0008394705000922042, 'subsample': 0.7414222684274389, 'colsample_bytree': 0.7500431124606814}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 20:33:56,865] Trial 7 finished with value: 0.956571256527989 and parameters: {'n_estimators': 694, 'max_depth': 8, 'learning_rate': 0.0054392414724914245, 'min_child_weight': 9, 'gamma': 0.0016380903759233036, 'reg_alpha': 0.5172521359138479, 'reg_lambda': 0.0011232525198171495, 'subsample': 0.9044580179273018, 'colsample_bytree': 0.6203727739289386}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 20:37:31,043] Trial 8 finished with value: 0.9567251385070593 and parameters: {'n_estimators': 988, 'max_depth': 12, 'learning_rate': 0.006679435225185046, 'min_child_weight': 4, 'gamma': 0.01582827123349121, 'reg_alpha': 84.36906819824333, 'reg_lambda': 0.005339116436914286, 'subsample': 0.8742904360117196, 'colsample_bytree': 0.9263995461424782}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 20:48:40,550] Trial 9 finished with value: 0.9585498482273872 and parameters: {'n_estimators': 1014, 'max_depth': 9, 'learning_rate': 0.010583361681950591, 'min_child_weight': 17, 'gamma': 4.897753360132409e-06, 'reg_alpha': 0.003928449217308657, 'reg_lambda': 1.9633038806713516e-07, 'subsample': 0.9560468277242485, 'colsample_bytree': 0.9458975074626715}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 20:51:15,655] Trial 10 finished with value: 0.9550431710693378 and parameters: {'n_estimators': 1755, 'max_depth': 2, 'learning_rate': 0.06979603321261876, 'min_child_weight': 30, 'gamma': 3.446997457417428, 'reg_alpha': 9.067523596797013e-05, 'reg_lambda': 15.732000675767004, 'subsample': 0.7297556947146414, 'colsample_bytree': 0.8278889020346141}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 20:52:56,170] Trial 11 finished with value: 0.9579895465008558 and parameters: {'n_estimators': 446, 'max_depth': 10, 'learning_rate': 0.012033847547464902, 'min_child_weight': 21, 'gamma': 2.273375346762444e-05, 'reg_alpha': 0.006843390459265405, 'reg_lambda': 3.167302750375694e-08, 'subsample': 0.9878648005010904, 'colsample_bytree': 0.8227235654205259}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 20:56:40,134] Trial 12 finished with value: 0.9581885063450463 and parameters: {'n_estimators': 1503, 'max_depth': 10, 'learning_rate': 0.03759652359872639, 'min_child_weight': 21, 'gamma': 2.4253338273153066e-05, 'reg_alpha': 0.0011383014428630617, 'reg_lambda': 6.242798736270291e-06, 'subsample': 0.9969290727268694, 'colsample_bytree': 0.8371999817696454}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 21:03:40,776] Trial 13 finished with value: 0.9586287734519093 and parameters: {'n_estimators': 1992, 'max_depth': 12, 'learning_rate': 0.011040416998061726, 'min_child_weight': 17, 'gamma': 2.6118586521792884e-05, 'reg_alpha': 0.3261996847640582, 'reg_lambda': 2.8230895097547192e-08, 'subsample': 0.9274168639164125, 'colsample_bytree': 0.7590450035024835}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 21:11:00,088] Trial 14 finished with value: 0.957361243416253 and parameters: {'n_estimators': 1934, 'max_depth': 12, 'learning_rate': 0.027669212124677812, 'min_child_weight': 26, 'gamma': 0.000269158104034817, 'reg_alpha': 0.6661350413910287, 'reg_lambda': 1.256664437519164e-08, 'subsample': 0.8211173249890097, 'colsample_bytree': 0.7504568188291959}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 21:18:03,866] Trial 15 finished with value: 0.954182167412594 and parameters: {'n_estimators': 1662, 'max_depth': 12, 'learning_rate': 0.07107548956063657, 'min_child_weight': 12, 'gamma': 0.03861595360819492, 'reg_alpha': 0.9427104399282265, 'reg_lambda': 3.544902140952283e-05, 'subsample': 0.9136622617914417, 'colsample_bytree': 0.7707437837458903}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 21:19:11,190] Trial 16 finished with value: 0.9565632155624844 and parameters: {'n_estimators': 220, 'max_depth': 10, 'learning_rate': 0.00840656795640989, 'min_child_weight': 21, 'gamma': 0.00023072777207527152, 'reg_alpha': 0.08211789523765249, 'reg_lambda': 2.0295138118459246e-06, 'subsample': 0.843373005692542, 'colsample_bytree': 0.8702415403485115}. Best is trial 4 with value: 0.9587043183875325.
[I 2026-10-10 21:25:35,624] Trial 17 finished with value: 0.958910926141265 and parameters: {'n_estimators': 1423, 'max_depth': 11, 'learning_rate': 0.013735365034512911, 'min_child_weight': 13, 'gamma': 1.9999543167310362e-06, 'reg_alpha': 6.906442415150357, 'reg_lambda': 9.5312610099552e-05, 'subsample': 0.9260074439454506, 'colsample_bytree': 0.7104877345208437}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 21:32:30,492] Trial 18 finished with value: 0.9587559361539371 and parameters: {'n_estimators': 1358, 'max_depth': 10, 'learning_rate': 0.018820158613501038, 'min_child_weight': 10, 'gamma': 1.6737035116796902e-06, 'reg_alpha': 9.585525998303904, 'reg_lambda': 0.0001252843065889276, 'subsample': 0.763667175708699, 'colsample_bytree': 0.697400417462611}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 21:39:47,669] Trial 19 finished with value: 0.9568352028511043 and parameters: {'n_estimators': 1493, 'max_depth': 9, 'learning_rate': 0.06102563808767083, 'min_child_weight': 9, 'gamma': 4.965112796846814e-07, 'reg_alpha': 4.291497939557108, 'reg_lambda': 0.000908591333990435, 'subsample': 0.6925284190541301, 'colsample_bytree': 0.6927233576772958}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 21:45:48,084] Trial 20 finished with value: 0.9554218829345787 and parameters: {'n_estimators': 1458, 'max_depth': 9, 'learning_rate': 0.1034327157767245, 'min_child_weight': 11, 'gamma': 1.9278135475896634e-06, 'reg_alpha': 3.439154460777863, 'reg_lambda': 0.06176092145519606, 'subsample': 0.7729042861422988, 'colsample_bytree': 0.7023950464582306}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 21:51:19,297] Trial 21 finished with value: 0.9588107308383763 and parameters: {'n_estimators': 1322, 'max_depth': 11, 'learning_rate': 0.018425760759834806, 'min_child_weight': 14, 'gamma': 1.491084083344878e-08, 'reg_alpha': 18.68374109208809, 'reg_lambda': 3.890397240830577e-05, 'subsample': 0.8795243930364637, 'colsample_bytree': 0.6624476183091353}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 21:58:46,364] Trial 22 finished with value: 0.9575175039766363 and parameters: {'n_estimators': 1657, 'max_depth': 11, 'learning_rate': 0.03648709800354278, 'min_child_weight': 12, 'gamma': 1.3613858810099068e-08, 'reg_alpha': 5.956351143777649, 'reg_lambda': 0.00011569055289809749, 'subsample': 0.8742487266664352, 'colsample_bytree': 0.6077545379780231}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 22:03:21,039] Trial 23 finished with value: 0.9576739027819056 and parameters: {'n_estimators': 1321, 'max_depth': 11, 'learning_rate': 0.016070030814416245, 'min_child_weight': 7, 'gamma': 2.785256570590173e-07, 'reg_alpha': 85.0046986303823, 'reg_lambda': 2.7000535095225723e-06, 'subsample': 0.7850736423568417, 'colsample_bytree': 0.6540571917682394}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 22:08:02,629] Trial 24 finished with value: 0.958052245788338 and parameters: {'n_estimators': 1434, 'max_depth': 10, 'learning_rate': 0.027224512876287445, 'min_child_weight': 13, 'gamma': 1.1585135172615065e-08, 'reg_alpha': 0.06635387154088526, 'reg_lambda': 0.0002332327114554039, 'subsample': 0.6081615021288252, 'colsample_bytree': 0.688455594414957}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 22:10:35,906] Trial 25 finished with value: 0.9579139976305404 and parameters: {'n_estimators': 705, 'max_depth': 11, 'learning_rate': 0.00938907104006079, 'min_child_weight': 19, 'gamma': 5.8086267493464595e-06, 'reg_alpha': 11.996171135214134, 'reg_lambda': 7.1244001367673835e-06, 'subsample': 0.8262488184329729, 'colsample_bytree': 0.7184162456655148}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 22:16:20,718] Trial 26 finished with value: 0.9588084053731928 and parameters: {'n_estimators': 1764, 'max_depth': 8, 'learning_rate': 0.014855565960046554, 'min_child_weight': 7, 'gamma': 2.5560261071419065e-06, 'reg_alpha': 1.3022717952791163, 'reg_lambda': 0.013897168081109119, 'subsample': 0.707421543105918, 'colsample_bytree': 0.6389541295059981}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 22:21:03,047] Trial 27 finished with value: 0.9568681604530415 and parameters: {'n_estimators': 1825, 'max_depth': 5, 'learning_rate': 0.007201558118938081, 'min_child_weight': 7, 'gamma': 0.00012164163385151885, 'reg_alpha': 1.4149828327169565, 'reg_lambda': 18.41785323753051, 'subsample': 0.6748681016837311, 'colsample_bytree': 0.6196837243753099}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 22:26:14,960] Trial 28 finished with value: 0.9588123876622392 and parameters: {'n_estimators': 1586, 'max_depth': 8, 'learning_rate': 0.013532081715884027, 'min_child_weight': 7, 'gamma': 2.7590282063061025e-07, 'reg_alpha': 0.10686618645966806, 'reg_lambda': 0.006033217586665223, 'subsample': 0.7116079820765531, 'colsample_bytree': 0.6574058164965032}. Best is trial 17 with value: 0.958910926141265.
[I 2026-10-10 22:30:14,717] Trial 29 finished with value: 0.9576182897693662 and parameters: {'n_estimators': 1591, 'max_depth': 7, 'learning_rate': 0.005178177262035867, 'min_child_weight': 1, 'gamma': 4.2089587232657813e-07, 'reg_alpha': 0.15119452469732816, 'reg_lambda': 4.465219922803195, 'subsample': 0.8887349430379016, 'colsample_bytree': 0.7870840316429115}. Best is trial 17 with value: 0.958910926141265.

Best CV ROC-AUC: 0.958910926141265
Best Parameters:
{'n_estimators': 1423, 'max_depth': 11, 'learning_rate': 0.013735365034512911, 'min_child_weight': 13, 'gamma': 1.9999543167310362e-06, 'reg_alpha': 6.906442415150357, 'reg_lambda': 9.5312610099552e-05, 'subsample': 0.9260074439454506, 'colsample_bytree': 0.7104877345208437}